fragment PageParts on Page {
  __typename
  title
  description
  seoTitle
  ogImage
  noIndex
  body
}

fragment ServiceParts on Service {
  __typename
  title
  slug
  description
  heroImage
  icon
  order
  features {
    __typename
    title
    description
  }
  faqs {
    __typename
    question
    answer
  }
  body
}

fragment PostParts on Post {
  __typename
  title
  description
  publishDate
  updatedDate
  image
  imageAlt
  category
  tags
  author
  readingTime
  status
  featured
  podcastEpisodeId
  podcastAudioUrl
  body
}

fragment TeamParts on Team {
  __typename
  name
  slug
  role
  image
  email
  phone
  linkedin
  order
  featured
  specialties
  body
}

fragment LocationParts on Location {
  __typename
  name
  slug
  country
  region
  description
  image
  order
  body
}

fragment EventParts on Event {
  __typename
  title
  slug
  description
  startDate
  endDate
  location
  locationType
  registrationUrl
  image
  featured
  includeInNewsletter
  body
}

fragment FaqParts on Faq {
  __typename
  question
  answer
  category
  order
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  tagline
  description
  logo
  logoWhite
  ogImage
  contact {
    __typename
    email
    phone
    address
    city
    province
    postalCode
  }
  social {
    __typename
    facebook
    instagram
    linkedin
    youtube
    twitter
  }
  cta {
    __typename
    title
    subtitle
    buttonText
    buttonUrl
  }
  newsletter {
    __typename
    title
    subtitle
    signupUrl
  }
  licenseInfo
}

fragment PopupParts on Popup {
  __typename
  name
  enabled
  trigger
  delay
  scrollPercent
  title
  content
  image
  buttonText
  buttonUrl
  pages
  startDate
  endDate
}
